// <auto-generated />
using System;
using EFrelationsANDmigrations.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EFrelationsANDmigrations.Migrations
{
    [DbContext(typeof(UniversityContext))]
    [Migration("20230420214911_AddedMentorBoolField")]
    partial class AddedMentorBoolField
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EFrelationsANDmigrations.Models.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("EFrelationsANDmigrations.Models.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsMentor")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("EFrelationsANDmigrations.Models.StudentsStudies", b =>
                {
                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudyId")
                        .HasColumnType("uuid");

                    b.HasKey("StudentId", "StudyId");

                    b.HasIndex("StudyId");

                    b.ToTable("StudentsStudies");
                });

            modelBuilder.Entity("EFrelationsANDmigrations.Models.Study", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Studies");
                });

            modelBuilder.Entity("EFrelationsANDmigrations.Models.Student", b =>
                {
                    b.HasOne("EFrelationsANDmigrations.Models.Group", "Group")
                        .WithMany("Students")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("EFrelationsANDmigrations.Models.StudentsStudies", b =>
                {
                    b.HasOne("EFrelationsANDmigrations.Models.Student", "Student")
                        .WithMany("StudentsStudies")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFrelationsANDmigrations.Models.Study", "Study")
                        .WithMany("StudentsStudies")
                        .HasForeignKey("StudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Study");
                });

            modelBuilder.Entity("EFrelationsANDmigrations.Models.Group", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("EFrelationsANDmigrations.Models.Student", b =>
                {
                    b.Navigation("StudentsStudies");
                });

            modelBuilder.Entity("EFrelationsANDmigrations.Models.Study", b =>
                {
                    b.Navigation("StudentsStudies");
                });
#pragma warning restore 612, 618
        }
    }
}
